; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mkrwifi1010]
platform = atmelsam
board = mkrwifi1010
framework = arduino
build_flags = 
	-DMNDEBUG
	-DTELNET
lib_deps = 
	arduino-libraries/WiFiNINA
	finitespace/BME280@^3.0.0
	khoih-prog/FlashStorage_SAMD
	symlink://../InputPin
	symlink://../OutputPin
lib_extra_dirs = 
	C:\PlatformIO_GlobalLibs
	F:\Users\Mark Naylor\OneDrive\Documents\Arduino\libraries
